from __future__ import annotations

import argparse
import os
import tempfile
from pathlib import Path

MPL_CACHE_DIR = Path(tempfile.gettempdir()) / "image_reconstruction_matplotlib"
MPL_CACHE_DIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(MPL_CACHE_DIR))
os.environ.setdefault("XDG_CACHE_HOME", str(MPL_CACHE_DIR))

import matplotlib
import pandas as pd
import seaborn as sns

matplotlib.use("Agg")
import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot model metrics from a run summary CSV.")
    parser.add_argument(
        "--results_csv",
        "--results-csv",
        dest="results_csv",
        type=Path,
        default=Path("outputs/kfold_results.csv"),
        help="Path to the CSV generated by train.py or a manually aggregated summary.",
    )
    parser.add_argument(
        "--output_path",
        "--output-path",
        dest="output_path",
        type=Path,
        default=Path("outputs/kfold_metrics_plot.png"),
        help="Where to write the rendered plot.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    df = pd.read_csv(args.results_csv)
    if "model" in df.columns and "model_type" not in df.columns:
        df = df.rename(columns={"model": "model_type"})
    if "psnr" in df.columns and "mean_psnr" not in df.columns:
        df = df.rename(columns={"psnr": "mean_psnr"})
    if "ssim" in df.columns and "mean_ssim" not in df.columns:
        df = df.rename(columns={"ssim": "mean_ssim"})
    if "latent_dim" not in df.columns:
        df = df.copy()
        df["latent_dim"] = range(1, len(df) + 1)

    df["model_type"] = df["model_type"].str.upper()
    sns.set_theme(style="whitegrid", context="talk")
    figure, axes = plt.subplots(1, 3, figsize=(20, 6))

    palette = sns.color_palette("deep", n_colors=df["model_type"].nunique())
    common_plot_args = {
        "data": df,
        "x": "latent_dim",
        "hue": "model_type",
        "linewidth": 3,
        "markersize": 10,
        "palette": palette,
    }

    sns.lineplot(y="mean_loss", marker="o", ax=axes[0], **common_plot_args)
    axes[0].set_title("Mean Loss (Lower is Better)", fontweight="bold")
    axes[0].set_ylabel("Mean Loss")
    axes[0].set_xlabel("Latent Dimension" if "latent_dim" in df.columns else "Run")

    sns.lineplot(y="mean_psnr", marker="s", ax=axes[1], **common_plot_args)
    axes[1].set_title("Mean PSNR (Higher is Better)", fontweight="bold")
    axes[1].set_ylabel("Mean PSNR (dB)")
    axes[1].set_xlabel("Latent Dimension" if "latent_dim" in df.columns else "Run")

    sns.lineplot(y="mean_ssim", marker="D", ax=axes[2], **common_plot_args)
    axes[2].set_title("Mean SSIM (Higher is Better)", fontweight="bold")
    axes[2].set_ylabel("Mean SSIM")
    axes[2].set_xlabel("Latent Dimension" if "latent_dim" in df.columns else "Run")

    figure.tight_layout()
    args.output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(args.output_path, dpi=300, bbox_inches="tight")
    print(f"Plot saved successfully to {args.output_path.resolve()}")


if __name__ == "__main__":
    main()
